FROM python:3.10-slim

RUN apt-get update
RUN apt-get install -y

RUN pip install --upgrade pip
RUN pip install pipenv

COPY Pipfile .
COPY Pipfile.lock .

RUN pipenv install --system --deploy --dev

WORKDIR /app


COPY . .

EXPOSE 3003

CMD ["python", "application.py"]