version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r blacklist/requirements.txt
      - pip install pytest coverage
  pre_build:
    - on-failure: ABORT
    commands:
      - echo Running pre-build commands...
      - pip install pytest pytest-cov
  build:
    - on-failure: ABORT
    commands:
      - echo Running tests with pytest...
      - set -e
      - pytest --maxfail=1 --disable-warnings
  post_build:
    - on-failure: ABORT
    commands:
      - echo Post-build commands...
  artifacts:
    files:
      - 'blacklist/**'
    discard-paths: yes