services:
  emails_db:
    container_name: emails_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - email_net
    
  emails:
    container_name: emails
    build: 
      context: ./blacklist
      dockerfile: Dockerfile
    image: blacklist:1.0
    ports:
      - "3000:3000"
    restart: always
    networks:
      - email_net
    depends_on:
      emails_db:
        condition: service_healthy

networks:
  email_net:
    driver: bridge